name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:

  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist/

      - name: Rename JAR using version
        run: |
          ORIGINAL_JAR=$(ls dist/srp-*.jar)
          mv "$ORIGINAL_JAR" "dist/srp-${{ inputs.version }}.jar"

      # Automatically generate release changelog based on conventional commits
      - name: Install conventional-changelog
        run: npm install conventional-changelog@7.1.1 conventional-changelog-conventionalcommits@9.1.0

      - name: Generate changelog
        id: changelog
        run: |
          node .config/changelog/changelog.mjs ${{ inputs.version }}
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Create a release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ steps.changelog.outputs.content }}
          draft: false
          allowUpdates: true
          replacesArtifacts: true
          prerelease: ${{ contains(inputs.version, '-SNAPSHOT') }}
          artifacts: dist/*.jar
          token: ${{ secrets.CI_CD_PAT }}

  # Add the version as an option in Deploy
  update-deploy-options:
    needs: create-release
    uses: ./.github/workflows/update-version.yml
    with:
      workflow-file: .github/workflows/deploy.yml
      version: ${{ needs.create-release.outputs.version }}
    secrets:
      TOKEN: ${{ secrets.CI_CD_PAT }}

  # Add the version as an option in Snapshot Promote
  update-promote-options:
    needs: [create-release, update-deploy-options]
    uses: ./.github/workflows/update-version.yml
    with:
      workflow-file: .github/workflows/promote-snapshot.yml
      version: ${{ needs.create-release.outputs.version }}
    secrets:
      TOKEN: ${{ secrets.CI_CD_PAT }}
