name: Build Release

on:
  release:
    types: [published]

jobs:
  download-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Create libs directory
        run: mkdir -p libs

      - name: Download Multiverse-Core
        run: |
          curl -L -o libs/Multiverse-Core-4.3.16.jar "${{ vars.MULTIVERSE_CORE_DOWNLOAD_URL }}"

      - name: Download Multiverse-NetherPortals
        run: |
          curl -L -o libs/Multiverse-NetherPortals-4.2.3.jar "${{ vars.MULTIVERSE_NETHERPORTALS_DOWNLOAD_URL }}"

      - name: Upload libs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: libs/

  build:
    runs-on: ubuntu-latest
    needs: download-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download libs artifact
        uses: actions/download-artifact@v4
        with:
          name: libs
          path: libs

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify libs directory
        run: ls -la libs/

      - name: Set Maven project version to release tag
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          mvn versions:set -DnewVersion=$RELEASE_TAG -DprocessAllModules

      - name: Build with Maven
        run: mvn clean package

      - name: Upload built JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: srp-jar
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download SRP JAR
        uses: actions/download-artifact@v4
        with:
          name: srp-jar
          path: ./

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: './srp-*.jar'
          remote_path: '/plugins/'
          sftp_only: true
          ssh_private_key: ''